### ISSUE TITLE
Alternative approach for resource bundle?

### ISSUE THREAD

**Issue by hwhw** [koreader/android-luajit-launcher#16] opened 2014-06-03 20:34 UTC
While the 7z-based approach works, it is a bit slow.
There are some ways we could circumvent that approach, partially or in total.
- the .lua files could go completely in the normal asset store, using the asset loader
- the .so libs could go into the libs folder of the Android project. Android will extract them to the NativeLibraryDir so we can access them with the loader (already implemented)
- the resources could be copied from the asset store OR
- the resources could use the .obb facility (Android native API includes "android/obb.h" and "android/storage_manager.h")

**Comment by pazos** [comment] 2019-07-16 21:06
Slightly related:

According to mobileread user **fbrzvnrnd** extracting the 7z could fail if the system has low memory during first start (or after an update).

A full log is attached on https://www.mobileread.com/forums/showpost.php?p=3864674&postcount=19

**Comment by Frenzie** [comment] 2019-07-16 21:33
Weird, I don't think my old 512 MB RAM phone ever displayed that problem even though it was always short on memory. We use the lowest compression level (`-mx=1`) so memory requirements are low as well.

**Comment by norbi24** [comment] 2019-08-11 08:55
I am facing the same problem on my Tolino Vision HD4 (512MByte RAM) - with august build.
Previously july build was working, but now I uninstalled august and reinstalled july build and it crashes in the same way after first startup.
In the  mobileread discussion mentioned above  Pazos wrote the problem was already solved ...

I looked into /data/data/org.koreader.launcher/files/libs and there are only two files - linjpeg.so.8 and libturbojpeg.so

Is ther a way to workaround this ? 

Line 178: E/KOReader( 2621): [main thread]: failed to run script: datastorage.lua:3: module 'libs/libkoreader-lfs' not found:
	Line 179: E/KOReader( 2621):      no field package.preload['libs/libkoreader-lfs']
	Line 180: E/KOReader( 2621):      no file 'libs/libkoreader-lfs.lua' (checked with asset loader)
	Line 181: E/KOReader( 2621):      no file 'libs/libkoreader-lfs.lua'
	Line 182: E/KOReader( 2621):      no file '/data/data/org.koreader.launcher/files/libs/libkoreader-lfs.lua'
	Line 183: E/KOReader( 2621):      no file 'libs/libkoreader-lfs.so'
	Line 184: E/KOReader( 2621):      no file '/data/data/org.koreader.launcher/files/libs/libkoreader-lfs.so'
	Line 185: E/KOReader( 2621): [main thread]: Stopping KOReader due to previous errors

**Comment by Frenzie** [comment] 2019-08-12 10:56
Nothing changed about the way resource extraction is handled. Solved in this context must mean solved for the user in question, perhaps by restarting the device or manually closing background apps to free up some memory.

I'm not really sure how to measure the memory use on Android; the profiler tool in Android Studio gives useless error messages that suggest it probably wouldn't work for non-Java stuff anyway. As I said or implied above, I don't think it can actually be much higher than about 5 MB for luajit+liblzma+buffer+dictionary, let's say 10 MB to be on the safe side, but it'd be nice to be sure. Unless we're talking about low internal storage it seems somewhat implausible that low memory can be much of a problem, but perhaps Android's "intelligent" memory recovery could get in the way.

For comparison, a very worst case scenario on my desktop maxes out at a whopping 6 MB while decompressing. That's with debug symbols and a bunch of large stardict dictionaries included in the archive.

```
# Thanks to https://superuser.com/a/767491
% TIMEFMT='%J   %U  user %S system %P cpu %*E total'$'\n'\
'avg shared (code):         %X KB'$'\n'\
'avg unshared (data/stack): %D KB'$'\n'\
'total (sum):               %K KB'$'\n'\
'max memory:                %M MB'$'\n'\
'page faults from disk:     %F'$'\n'\
'other page faults:         %R'
frenzie-desktop% time 7z x koreader-v2019.08-2-g53b77e3a_2019-08-11.7z   

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (306C3),ASM,AES-NI)

Scanning the drive for archives:
1 file, 97080660 bytes (93 MiB)

Extracting archive: koreader-v2019.08-2-g53b77e3a_2019-08-11.7z
--
Path = koreader-v2019.08-2-g53b77e3a_2019-08-11.7z
Type = 7z
Physical Size = 97080660
Headers Size = 11890
Method = LZMA2:16 BCJ
Solid = +
Blocks = 16

Everything is Ok                                       

Folders: 141
Files: 803
Size:       227493718
Compressed: 97080660
7z x koreader-v2019.08-2-g53b77e3a_2019-08-11.7z   3.91s  user 0.12s system 100% cpu 4.025 total
avg shared (code):         0 KB
avg unshared (data/stack): 0 KB
total (sum):               0 KB
max memory:                6 MB
page faults from disk:     0
other page faults:         778
```

**Comment by pazos** [comment] 2019-08-12 13:13
> I'm not really sure how to measure the memory use on Android; the profiler tool in Android Studio gives useless error messages that suggest it probably wouldn't work for non-Java stuff anyway. As I said or implied above,

What kind of errors?. I run the (memory) profiler just fine with my phone attached to usb and it is reporting both java and native memory usage. (Native means both the jni used internally by android and our shared libraries).

**Comment by Frenzie** [comment] 2019-08-12 13:35
Specifically "Please select Android SDK", and pretending that's something to set up in the profiling section (it's not). It's also complaining about a supposed lack of JDK, even though all of that kind of stuff is seemingly set up judging by various other dialogs (settings, project structure). Android Studio is a shitshow. But I guess I've been using this copy since the 2.x days, so I suppose I could consider wiping the whole thing and starting from scratch. I don't really want to lose my VMs though, if possible.

Anyway, in that case you can easily confirm whether I'm correct that it should be <10 MB during the initial extraction phase, or perhaps I should say <30-40 MB depending on how much the Java part of the equation weighs.

**Comment by pazos** [comment] 2019-08-12 15:00
KOReader uses much more memory than that on early init (when extracting assets):

![Captura de pantalla 2019-08-12 a las 16 54 32](https://user-images.githubusercontent.com/975883/62874657-f1cfab00-bd21-11e9-946e-29acab38441f.png)

On a normal start (ie: assets were already extracted) it uses less memory:

![Captura de pantalla 2019-08-12 a las 16 58 48](https://user-images.githubusercontent.com/975883/62875050-95b95680-bd22-11e9-9a35-ca94f38b8485.png)

**Comment by pazos** [comment] 2019-08-12 15:05
On my tests  I can reproduce the following things:

- When extracting assets we reach (on my device with 3gb ram) more than 300mb of ram usage
- While using CRengine memory usage is about 60-70mb
- While using MuPDF memory usage is about 110-120mb. (With reflow enabled it reachs to 320 mb bun never passes that value).

**Comment by Frenzie** [comment] 2019-08-12 15:47
Hm, interesting. Guess I'll try purging settings and if that doesn't work reinstalling Android Studio. (Actually it might go back to 1.x). It's probably easier if perhaps less interesting to drop this 7z extraction method though.

**Comment by Frenzie** [comment] 2019-08-12 16:04
@pazos I deleted all the ~/.AndroisStudiox.x stuff; it redownloaded everything and everything seems to be as new, but the error persists.

![Screenshot_2019-08-12_17-56-17](https://user-images.githubusercontent.com/202757/62879049-9655eb00-bd2a-11e9-9755-f3c2ac8f79e8.png)

![Screenshot_2019-08-12_18-02-26](https://user-images.githubusercontent.com/202757/62879418-5d6a4600-bd2b-11e9-927b-de692d015715.png)

(Also why is this Darcula theme so absurdly low contrast.)

**Comment by pazos** [comment] 2019-08-12 16:12
@Frenzie:

1. Build a debug variant of KOReader for your phone or the emulator with `kodev`
2. Once built go to Android Studio -> import project -> select koreader/platform/android/luajit-launcher.
3. It will ask you which SDK do you want to use:
![Sin nombre](https://user-images.githubusercontent.com/975883/62879829-4546f680-bd2c-11e9-945c-912971bcc072.png)

Choose "Use Android Studio SDK" as it is probably the place where you configured your AVDs.

Now you can go to File->Profile or debug APK and select your prebuilt debug apk. You can choose any device/emulator with Android 6.0 or higher to run it.

**Comment by Frenzie** [comment] 2019-08-12 16:20
As it turns out Android Studio simply lied through its teeth when it claimed this:

![Screenshot_2019-08-12_18-20-27](https://user-images.githubusercontent.com/202757/62880531-e2eef580-bd2d-11e9-9b59-fd08d3e19130.png)

**Comment by norbi24** [comment] 2019-08-12 18:20
@Frenzie, is there a way to uncompress the koreader-xxx.7z manually per adb command just after the setup ? So that koreader would find all libs etc already there to avoid this memory intensive startup step on devices with low RAM

**Comment by Frenzie** [comment] 2019-08-12 20:02
@norbi24 If you put them in /data/data/org.koreader.launcher/files (assuming that's the right directory on your device) then that should do the trick as a workaround.

```
adb push /directory/on/your/pc /data/data/org.koreader.launcher/files
```

**Comment by Frenzie** [comment] 2019-08-12 20:45
@pazos It looks like ye olde LZMA reaches a max of about 26 MB while decompressing, in my aforementioned super worst case scenario.

![Screenshot_2019-08-12_22-38-28](https://user-images.githubusercontent.com/202757/62896753-fa3fda00-bd51-11e9-9bbd-9031ece37837.png)

Since LZMA2 can do multithreaded decoding a minor increase in memory might make sense, but I can't really make heads or tails of 200+ MB.

I might look into it a little more, but the easy solution is to remove that 2 from `lzma2` where I added it a while back.

**Comment by pazos** [comment] 2019-08-12 22:38
> I might look into it a little more, but the easy solution is to remove that 2 from lzma2 where I added it a while back

Yes, sir :+1: 

In the long run we might want to implement what @hwhw said:

> the .so libs could go into the libs folder of the Android project. Android will extract them to the NativeLibraryDir so we can access them with the loader.

In order to reduce disk space because we have the assets compressed on the apk, and uncompressed on NativeLibraryDir and it would be nice to avoid duplicities.

The *Android will extract them to the NativeLibraryDir so we can access them with the loader.* happens if the app is installed by the user. In the case of a system app we might need to copy libraries to `/system/priv-app/KOReader/$ARCH/lib` (for 4.3+, without clashing with system libraries) or to `/system/lib` (for 4.2-, in this case some libs might clash with system libs, ie: openssl).

**Comment by norbi24** [comment] 2019-08-13 09:15
@Frenzie, as I tried to copy the files per asb push to my Tolino ereader, it reported there was not enough space on the system partition ...  so it is clear now that my main problem was not low RAM, 
but the system partition which is anyway only 512 MByte ...  I now restored per TWRP one two month old backup which worked fine with koreader 2019.04, uninstalled it and installed 2019.08 and it works fine ...  sorry fo the confusion.
However,  wouldn't it be better from the UX prerspective to inform the user during the first startup of koreader that some files are still to be extracted ... like giving him a pop saying 
"Extracting libraries ... please wait" or so, and if it succeeds, simply continue but if the process terminates with error, inform the user about the possible reason (according to the error code captured). As now it looks like a crash ... if had got such a error on the screen, I would have solved it on my own without having disturbed you all guys

**Comment by Frenzie** [comment] 2019-08-13 09:33
@pazos Having played around a little, I think the memory use might be related to the memory available to Android itself. So on our high-memory devices/emulators it gobbles up a few 100  apparently, but on a lower memory device it has no trouble.

This is what it looks like in 128 MB:

![Screenshot_2019-08-13_11-32-26](https://user-images.githubusercontent.com/202757/62931134-14170680-bdbe-11e9-94c9-3d471db69b52.png)

So https://github.com/koreader/koreader/pull/5200 with associated slowdown may not be necessary (plus as stated we want to move the libs anyway).

**Comment by Frenzie** [comment] 2019-08-13 10:04
@norbi24 It does do that, kind of. Just no error handling, which is of course stupid.

It's surprisingly hard to create a condition where you have enough space to install the program but not enough to extract the resources. :-D

**Comment by norbi24** [comment] 2019-08-21 08:43
@Frenzie,  would someone who is experienced in these installation scripts add the error condition check and then show some error like "Libraries could not be extracted due to ... low space ... ", I could play around on my Tolino with it and test it like this: 
1. At first take care there is enought room in system to install Koreader
2. Then copy a lot of dummy data to the system partition (shoud work on a rooted device)
3. Then start KOReader and check the error message 

Actually I can not judge how many ereaders are there around with only 512 Megs but if there are some, I can imagine that some guys try to install KOReader and on the first crash they uninstall it and go on searching another app ... (like me one year ago) 
Please let me know

**Comment by Frenzie** [comment] 2019-08-21 09:17
@norbi24 We don't require any assistance with testing low-space conditions, thanks for offering though!

You see, RAM and storage are simple settings in the Android emulator:

![Screenshot_2019-08-21_11-10-11](https://user-images.githubusercontent.com/202757/63418992-49e26d80-c404-11e9-9692-c02013f4d8f9.png)

Also keep in mind this ticket is about moving away from the very approach. :-)

**Comment by pazos** [comment] 2021-03-25 13:01
I'm going to close this ticket. There's nothing we can do to keep the minimum API in 14. Shared libraries must be placed on filesDir because there's no way to retrieve its path from libsDir. Something like that won't happen if we bump the minimum API to  23 (Android M), but that's another topic.

For now dloading libs from filesDir works fine targeting/in Android 11, but triggers an SELinux audit warning.  Maybe someday will be forbidden. Until then we're good.

IE: for binaries is actually forbidden in APIs >= 28, so the approach in #276 is required to bump the API and keep sdcv working

**Closed by pazos** 2021-03-25 13:01 UTC
